SetracoRecrutement/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('config.urls')),
    path('', include('profiles.urls')),
    path('', include('accounts.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

config/urls.py
from django.urls import path

from .views import (config_view, create_skill, create_state, delete_skill,
                    delete_state, create_training, delete_training)
from .views_ajax import skills_data, states_data, trainings_data

urlpatterns = [
    path('config/', config_view, name='config'),

    path('create_skill/', create_skill, name='create_skill'),
    path('delete_skill/', delete_skill, name='delete_skill'),

    path('create_state/', create_state, name='create_state'),
    path('delete_state/', delete_state, name='delete_state'),

    path('create_training/', create_training, name='create_training'),
    path('delete_training/', delete_training, name='delete_training'),

    # ajax
    path('skills_data/', skills_data, name="skills_data"),
    path('states_data/', states_data, name="states_data"),
    path('trainings_data/', trainings_data, name="trainings_data"),
]

profiles/urls.py
from django.urls import path

from .views import (config, profile_delete, profiles_create,
                    profiles_view, error_page)
from .views_ajax import (check_profile, delete_comment, delete_followup, delete_file,
                         export_profile_pdf, export_profiles_csv,
                         profiles_data)

urlpatterns = [
    path('', profiles_view, name='profiles'),
    path('profiles/', profiles_view, name='profiles'),
    path('error/', error_page, name='error_page'),
    path('profile_delete', profile_delete, name='profile_delete'),
    path('profiles_create', profiles_create, name="profiles_create"),


    # ajax
    path('profiles_data', profiles_data, name='profiles_data'),
    path('check_profile/', check_profile, name='check_profile'),
    path('export_profiles_csv/', export_profiles_csv,
         name='export_profiles_csv'),
    path('export_profile_pdf/',
         export_profile_pdf, name='export_profile_pdf'),
    path('delete_comment/', delete_comment, name="delete_comment"),
    path('delete_followup/', delete_followup, name="delete_followup"),
    path('delete_file/', delete_file, name='delete_file')
]

profiles/models.py
from django import forms
from django.contrib.auth.models import User
from django.db import models
from django.dispatch import receiver
from django.core.validators import FileExtensionValidator
import os

from config.models import Skill, State, Training


class Profile(models.Model):
    name = models.CharField(max_length=100)
    surname = models.CharField(max_length=100)
    email = models.EmailField(unique=False)
    number = models.CharField(max_length=20)
    town = models.CharField(max_length=100)
    skills = models.ManyToManyField(Skill, related_name='profiles')
    trainings = models.ManyToManyField(Training, related_name='trainings')
    state = models.ForeignKey(
        State, on_delete=models.SET_NULL, null=True, blank=True)

    diplomas = models.TextField(blank=True)  # Multiline string, use TextField
    # birthday = models.DateField(null=True, blank=True)
    birthday = models.CharField(max_length=50, default="")
    creation_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} {self.surname} {self.state} {self.skills} {self.trainings} ...]"


class Comment(models.Model):
    profile = models.ForeignKey(
        Profile, related_name='comments', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Comment by {self.user.username} on {self.creation_date}"

class FollowUp(models.Model):
    profile = models.ForeignKey(
        Profile, related_name='followups', on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    text = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"FollowUp by {self.user.username} on {self.creation_date}"

class ProfileFile(models.Model):
    profile = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name='files')
    file = models.FileField(upload_to='profile_files/')
    allowed_extensions = ['jpg', 'jpeg', 'png', 'pdf', 'docx']
    validator = FileExtensionValidator(allowed_extensions=allowed_extensions)

    def __str__(self):
        return f"File for {self.profile.name} {self.profile.surname}"

@receiver(models.signals.post_delete, sender=ProfileFile)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """
    Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if instance.file:
        if os.path.isfile(instance.file.path):
            os.remove(instance.file.path)

profiles/forms.py
from django import forms

from .models import Comment, Profile, ProfileFile, FollowUp


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['name', 'surname', 'email',
                  'number', 'town', 'skills', 'diplomas']
        widgets = {
            'skills': forms.CheckboxSelectMultiple(),  # To handle ManyToManyField
            'diplomas': forms.Textarea(attrs={'rows': 4}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 3}),
        }

class FollowUpForm(forms.ModelForm):
    class Meta:
        model = FollowUp
        fields = ['text']
        widgets = {
            'text': forms.Textarea(attrs={'rows': 3}),
        }

class ProfileFileForm(forms.ModelForm):
    class Meta:
        model = ProfileFile
        fields = ['file']

profiles/views.py
from django.contrib.auth.decorators import (login_required,
                                            permission_required,
                                            user_passes_test)
from django.db import transaction
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse
from django.views.decorators.http import require_http_methods
from django.core.exceptions import ValidationError
from SetracoRecrutement.logger import Logger
from config.models import Skill, State, Training

from .models import Comment, Profile, ProfileFile, FollowUp
from django.core.exceptions import PermissionDenied

logger = Logger('profiles')


def error_page(request):
    error_message = request.GET.get('message', 'Erreur inconnue')
    return render(request, 'error.html', {'error_message': error_message})


@login_required
def config(request):
    if request.method == 'GET':
        skills = Skill.objects.all()
        return render(request, 'config.html', {'skills': skills})


#@permission_required('profiles.view_profile', raise_exception=True)
@login_required
def profiles_view(request):
    is_superuser = request.user.is_superuser

    is_editor_or_admin = request.user.groups.filter(
        name__in=['Editeur', 'Admin']).exists()

    is_editor_or_admin_or_superuser = is_superuser or is_editor_or_admin

    return render(request, 'profiles.html', {'is_editor_or_admin': is_editor_or_admin_or_superuser})


def has_add_or_change_permission(user):
    if not (user.has_perm('profiles.add_profile') or user.has_perm('profiles.change_profile')):
        raise PermissionDenied  # Raises the exception when permissions are lacking
    return True


@transaction.atomic
@login_required
@user_passes_test(has_add_or_change_permission)
@require_http_methods(["POST"])
def profiles_create(request):
    profile_id = request.POST.get('id')
    try:
        logger.info(
            f"{'Updating' if profile_id else 'Creating'} profile {request.POST}", request=request)
        logger.debug(
            f"request data {request.POST}", request=request)
        surname = request.POST.get('surname')
        name = request.POST.get('name')
        town = request.POST.get('town')
        email = request.POST.get('email')
        number = request.POST.get('number')
        birthday = request.POST.get('birthday')
        diplomas = request.POST.get('diplomas')
        comment = request.POST.get('comment')
        followup = request.POST.get('followup')
        skill_ids = request.POST.get('skills', '')
        training_ids = request.POST.get('trainings', '')
        state_id = request.POST.get('state', None)
        files = request.FILES.getlist('files')

        profile = get_object_or_404(
            Profile, id=profile_id) if profile_id else Profile()

        profile.surname = surname
        profile.name = name
        profile.town = town
        profile.email = email
        profile.number = number
        profile.birthday = birthday
        profile.diplomas = diplomas
        profile.state = State.objects.filter(
            id=state_id).first() if state_id else None

        profile.save()

        if comment:
            Comment.objects.create(
                profile=profile,
                user=request.user,
                text=comment
            )

        if followup:
            FollowUp.objects.create(
                profile=profile,
                user=request.user,
                text=followup
            )

        if skill_ids:
            selected_skill_ids = list(map(int, skill_ids.split(',')))
            selected_skills = Skill.objects.filter(id__in=selected_skill_ids)
            profile.skills.set(selected_skills)
        else:
            profile.skills.clear()

        if training_ids:
            selected_training_ids = list(map(int, training_ids.split(',')))
            selected_trainings = Training.objects.filter(
                id__in=selected_training_ids)
            profile.trainings.set(selected_trainings)
        else:
            profile.trainings.clear()

        for file in files:
            try:
                ProfileFile.validator(file)
                ProfileFile.objects.create(profile=profile, file=file)
            except ValidationError as e:
                logger.error(
                    f"Wrong extension file is uploaded {e}", request=request)
                return render(request, 'error.html', {'error_message': "Erreur lors de la création/mise à jour du profile, mauvais type de fichier"})
    except Exception as e:
        logger.error(f"Error creating profile {e}", request=request)
        return render(request, 'error.html', {'error_message': "Erreur lors de la création/mise à jour du profile"})

    return redirect('/profiles')


@login_required
@permission_required('profiles.delete_profile', raise_exception=True)
@require_http_methods(["DELETE"])
def profile_delete(request):
    profile_id = request.GET.get('id')
    logger.info(f"Deleting profile by id: {profile_id}", request=request)
    try:
        if profile_id:
            Profile.objects.filter(id=profile_id).delete()
    except Exception as e:
        logger.error(
            f"Error deleting profile by id: {profile_id} {e}", request=request)

    return redirect('/profiles')

profiles/templates/components/comments_list.html
<v-card flat style="flex-basis: 100%">
    <v-card-title>Commentaires</v-card-title>
    <v-card-text>
        <v-timeline align="start" side="end">
            <v-timeline-item v-for="(com, i) in item.comments" :key="i">
                <template v-slot:icon><span class="text-white">${i + 1}</span></template>
                <v-card>
                    <v-card-title class="text-subtitle-1">
                        ${com.user.username} - ${com.creation_date}</v-card-title>
                    <v-card-text class="bg-white text--primary">
                        <v-row>
                            <v-col cols="10" style="word-break: break-word;">
                                <p>${ com.text }</p>
                            </v-col>
                            <v-col cols="2" class="d-flex justify-center align-center">
                                {% if perms.profiles.delete_comment %}
                                <v-icon size="36" color="grey-darken-3" @click="deleteComment(com)">mdi-delete</v-icon>
                                {% endif %}
                            </v-col>
                        </v-row>
                    </v-card-text>
                </v-card>
            </v-timeline-item>
        </v-timeline>
    </v-card-text>
</v-card>

profiles/templates/components/file_list.html
<v-card-title v-if="true">Fichier(s)</v-card-title>
<v-card-text v-if="true">
    <v-row no-gutters class="w-full" style="overflow: hiddenn; width: 100%;">
        <v-col class="pa-1" cols="6" v-for="file in item.files" :key="file.id">
            <v-hover v-slot="{ isHovering, props }">
                <v-card class="mx-auto" color="grey-lighten-4" max-width="600" v-bind="props">
                    <v-card-title>
                        ${file.file_name}
                    </v-card-title>
                    <v-overlay id="overlay" :model-value="!!isHovering" style="z-index: 9999; top: 0px"
                        class="d-flex justify-center align-center w-100 h-100" scrim="#036358" contained>
                        <div class="d-flex justify-space-around align-center transition-fast-in-fast-out bg-blue-lighten-2
                                                                                v-card--reveal "
                            style="height: 100%; width: 100%;">
                            <v-icon color="white" @click="openFile(file)">mdi-eye</v-icon>
                            <v-icon color="white" @click="printFile(file)">mdi-printer</v-icon>
                            {% if perms.profiles.delete_profilefile %}
                            <v-icon color="white" @click="deleteFile(file)">mdi-delete</v-icon>
                            {% endif %}
                        </div>
                    </v-overlay>
                </v-card>
            </v-hover>
        </v-col>
    </v-row>
</v-card-text>

profiles/templates/components/followups_list.html
<v-card v-if="true" flat style="flex-basis: 100%">
    <v-card-title>Suivi interne</v-card-title>
    <v-card-text>
        <v-timeline align="start" side="end">
            <v-timeline-item v-for="(flw, i) in item.followups" :key="i" :dot-color="i%2==0? 'pink': 'teal-lighten-3'">
                <v-card>
                    <v-card-title class="text-subtitle-1">
                        ${flw.user.username} - ${flw.creation_date}
                    </v-card-title>
                    <v-card-text class="bg-white text--primary">
                        <v-row>
                            <v-col cols="10" style="word-break: break-word;">
                                <p>${flw.text}</p>
                            </v-col>
                            <v-col cols="2" class="d-flex justify-center align-center">
                                {% if perms.profiles.delete_followup %}
                                <v-icon size="36" color="grey-darken-3" @click="deleteFollowup(flw)"> mdi-delete
                                </v-icon>
                                {% endif %}
                            </v-col>
                        </v-row>
                    </v-card-text>
                </v-card>
            </v-timeline-item>
        </v-timeline>
    </v-card-text>
</v-card>

profiles/templates/components/personal_info.html
<v-card-title>Données personnelles</v-card-title>
<v-card-text>
    <v-row class="align-center">
        <v-col cols="auto"><v-icon large>mdi-email</v-icon></v-col>
        <v-col><p class="text-body-1">${item.email}</p></v-col>
    </v-row>
    <v-row class="align-center">
        <v-col cols="auto"><v-icon large>mdi-phone</v-icon></v-col>
        <v-col><p class="text-body-1">${item.number}</p></v-col>
    </v-row>
    <v-row class="align-center">
        <v-col cols="auto"><v-icon large>mdi-account-school</v-icon></v-col>
        <v-col><p class="text-body-1">${item.diplomas}</p></v-col>
    </v-row>
    <v-row class="align-center">
        <v-col cols="auto"><v-icon large>mdi-calendar-range</v-icon></v-col>
        <v-col><p class="text-body-1">${item.birthday}</p></v-col>
    </v-row>
</v-card-text>